language: node_js

cache:
  yarn: true
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn

script:
  - yarn build
  - yarn checkpack -- vanillajs -e test/checkpack.ts --validate
  - yarn checkpack -- browserify -e test/checkpack.ts --validate
  - yarn checkpack -- webpack -e test/checkpack.ts --validate
