name: Latest PixiJS Node.js CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2
              with:
                path: tilemap
            - name: Go into tilemap directory
              run: cd tilemap && ls
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Setup relativeDependencies
              uses: r26d/jq-action@master
              with:
                cmd: >
                  jq '.relativeDependencies = { "@pixi/canvas-renderer": "../pixi.js/packages/canvas/renderer", "@pixi/constants": "../pixi.js/packages/constants", "@pixi/core": "../pixi.js/packages/core", "@pixi/display": "../pixi.js/packages/display", "@pixi/graphics": "../pixi.js/packages/graphics", "@pixi/math": "../pixi.js/packages/math", "@pixi/utils": "../pixi.js/packages/utils" }' ./package.json > package2.json && mv package2.json package.json
            - name: Checkout PixiJS
              uses: actions/checkout@v2
              with:
                repository: pixijs/pixi.js
                path: pixi.js
            - name: List dir
              run: cd .. && ls && cd tilemap
            - name: Install dependencies
              run: yarn
            - name: Build & type-checking
              run: yarn build
            - name: Lint
              run: yarn lint
            - uses: GabrielBB/xvfb-action@v1.0
              with:
                name: Unit testing
                run: yarn unit-test


